### ISSUE TITLE
난이도 선택 문제

### ISSUE THREAD

**Issue by kbsooo** [Kbyungs/OOPSubmarine#2]
난이도 선택하고 난 후 
난이도 선택이 완료되었습니다. 선택된 난이도는 Intermediate입니다.
이 문구가 뜨는데
조금 진행하다 보면 한번 더 뜸

**Comment by dongho-dev** [comment]
함수에 sendtoall로 뿌리는거 이미 있어서 if문에 있던거 지워서 해결 완료
