### ISSUE TITLE
칸 숫자 문제

### ISSUE THREAD

**Issue by kbsooo** [Kbyungs/OOPSubmarine#5]
지금 난이도 선택에 따라서 맵의 가장자리를 커팅하는 방식 같음
그래서 쉬운 난이도로 갈 수록 맵의 가장자리가 커팅되어서 가장 오른쪽 열, 가장 밑 행은 숫자힌트가 맞지 않음

그래서 자르는 방식이 아니라
난이도에 따라서 처음 맵 설정부터 다시 해야 할듯
ex) beginner -> mine 각각 3개, treasure 총 5개,  맵 크기 5*5
intermediate -> mine 각각 5개, treasure 총 7개, 맵 크기 7*7
expert -> mine 각각 8개, treasure 총 7개, 맵 크기 8*8

**Comment by dongho-dev** [comment]
아니면 맵은 그대로 두고 expert는 라이프 1개로 고정한다던가 하는건 어떰

**Comment by kbsooo** [comment]
그것도 ㄱㅊ
근데 근본적인 문제점이 맵의 크기에 비해서 보물이나 지뢰의 갯수가 너무 적음
그래서 그냥 목숨가지고 노는것도 괜찮을듯

**Comment by kbsooo** [comment]
난이도 sibal
