### ISSUE TITLE
게임 운영 관련 문제

### ISSUE THREAD

**Issue by kbsooo** [Kbyungs/OOPSubmarine#7]
폭탄에 비해서 보물의 갯수가 너무 많아서 
죽고싶어도 죽을 수가 없음

**Comment by dongho-dev** [comment]
보물에 라이프 회복하는거를 없애거나 줄여야 할듯

**Comment by kbsooo** [comment]
체력을 줄이는것도 괜찮을듯
맵 사이즈를 좀 줄이거나
